class TextHelper {
  TextHelper._();
  static const noData = 'No data';
  static const fixIssues = 'Fix issues';
  static const register = 'Register';
  static const submit = 'Submit';
  static const signupPage = 'Signup Page';
  static const intro = 'Intro';
  static const introDesc1 = 'Intro Desc 1';
  static const introDesc2 = 'Intro Desc 2';
  static const smallSignup = 'Small Signup';
  static const start = 'Start';
  static const signup = 'Signup';
  static const title = "Google Sign In";
  static const textIntro = "Growing your \n business is ";
  static const textIntroDesc1 = "easier \n ";
  static const textIntroDesc2 = "then you think!";
  static const textSmallSignUp = "Sign up takes only 2 minutes!";
  static const textSignIn = "Sign In";
  static const textSignUpBtn = "Sign Up";
  static const textStart = "Get Started";
  static const textSignInTitle = "Welcome back!";
  static const textRegister = "Register Below!";
  static const textSmallSignIn = "You've been missed!";
  static const textSignInGoogle = "Sign In With Google";
  static const textAcc = "Don't have an account? ";
  static const textSignUp = "Sign Up here";
  static const textHome = "Home";
  static const textNoData = "No Data Available!";
  static const textFixIssues = "Please fill the data correctly!";
}
