name: flutter_firebase_bloc_with_peter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  cupertino_will_pop_scope: ^1.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_inappwebview: ^5.4.3+7
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  in_app_update: ^3.0.0
  overlay_support: ^2.0.1
  package_info: ^2.0.2
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
