// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXl0kFIQLtgy6bepqoqnfBXdzgkX479_Y',
    appId: '1:753805890923:web:7bdd8ff10224288309682e',
    messagingSenderId: '753805890923',
    projectId: 'fir-bloc-with-peter',
    authDomain: 'fir-bloc-with-peter.firebaseapp.com',
    storageBucket: 'fir-bloc-with-peter.appspot.com',
    measurementId: 'G-SB6E5ZEW3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqRWZ9IKenQ7Xpx799mJGB3yKgpMpqFDE',
    appId: '1:753805890923:android:5c2c2dc8de833ce109682e',
    messagingSenderId: '753805890923',
    projectId: 'fir-bloc-with-peter',
    storageBucket: 'fir-bloc-with-peter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFH-tk-Wz9nHP2AVWEjdu52BuHN93zBes',
    appId: '1:753805890923:ios:2ee9c73e37e06fd109682e',
    messagingSenderId: '753805890923',
    projectId: 'fir-bloc-with-peter',
    storageBucket: 'fir-bloc-with-peter.appspot.com',
    iosClientId: '753805890923-t7ba0d4klanhmskeauj82mm74ndtk05l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseBlocWithPeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFH-tk-Wz9nHP2AVWEjdu52BuHN93zBes',
    appId: '1:753805890923:ios:2ee9c73e37e06fd109682e',
    messagingSenderId: '753805890923',
    projectId: 'fir-bloc-with-peter',
    storageBucket: 'fir-bloc-with-peter.appspot.com',
    iosClientId: '753805890923-t7ba0d4klanhmskeauj82mm74ndtk05l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseBlocWithPeter',
  );
}
